image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS clean test

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test jacoco:report
  artifacts:
    paths:
      - client/target/site/jacoco/
      - server/target/site/jacoco/
      - shared/target/site/jacoco/

#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master
